### ISSUE TITLE
Keep downgrading to previous PHP versions?

### ISSUE THREAD

**Issue by leoloso** [szepeviktor/rectorize#1]
`DowngradeSetList::PHP_80` downgrades to PHP 7.4 only. 

If you want, you can keep downgrading to previous versions, all the way to 7.1. That could be an input to the GitHub Action.

**Comment by szepeviktor** [comment]
Adding many options can be done in a fork.

Could you please try the patch branch?
https://github.com/szepeviktor/rectorize/actions?query=workflow%3ARectorize
You may input: 7.4 7.3 7.2 7.1 7.0 or 5.6
I hope you like it!
