### ISSUE TITLE
Add SKIP as an input?

### ISSUE THREAD

**Issue by leoloso** [szepeviktor/rectorize#2]
Some libraries may produce some issues when applying Rector on them, so we must add some of their files to `Option::SKIP` in the Rector config to avoid the process from exiting with error.

For instance, that happens in my project with a few of Symfony's libraries, when downgrading only PROD libraries (you're also downgrading DEV, so I guess this problem will not happen for you), and I must add [this code](https://github.com/leoloso/PoP/blob/master/rector-downgrade-code.php#L35:L44):

```php
    $parameters->set(Option::SKIP, [
        // Ignore errors from classes we don't have in our environment,
        // or that come from referencing a class present in DEV, not PROD
        __DIR__ . '/vendor/symfony/cache/Adapter/MemcachedAdapter.php',
        __DIR__ . '/vendor/symfony/cache/DoctrineProvider.php',
        __DIR__ . '/vendor/symfony/cache/Messenger/EarlyExpirationHandler.php',
        __DIR__ . '/vendor/symfony/string/Slugger/AsciiSlugger.php',
    ]);
```

Since anyone using `rectorize` will have a different project, with different libraries installed, maybe you can provide an input to define what files to skip. Or not. Up to you.

**Comment by szepeviktor** [comment]
Adding many GitHub Actions manual workflow options would lead to a highly complicated project.

Please fork this project and edit `rector.php`. 👀
