### ISSUE TITLE
Add documentation: What PHP 8 features are supported?

### ISSUE THREAD

**Issue by leoloso** [szepeviktor/rectorize#3]
Rector only downgrades certain features from PHP 8.0, the ones tackled by [these rules](https://github.com/rectorphp/rector/blob/master/config/set/downgrade-php80.php#L21), and not all new features.

So, for instance, there is no downgrade rule for [named arguments](https://www.php.net/releases/8.0/en.php#named-arguments). If the code is using them, the downgraded code will still have them, and then running it on PHP 7.4 will 💣 boom 💥!

(The issue for named arguments was [created but not implemented](https://github.com/rectorphp/rector/issues/4155), and now it's closed... and like that, there may be others)

So, I think you should explain in your README what are all the supported PHP 8.0 features, like I'm doing [here](https://github.com/leoloso/PoP#supported-php-features), to avoid users having their code 💣 boom 💥

**Comment by szepeviktor** [comment]
> 💣 boom 💥!

Working on this...

**Comment by szepeviktor** [comment]
Done. https://github.com/szepeviktor/rectorize/commit/a30e4cdf1b1c7c9f3b3a52280f6ee9c2279d3b82
Your PR is welcome!

**Comment by leoloso** [comment]
Can. I haven't downgraded from PHP 8.0 yet on my project, so I don't know which are all the supported features. But yes, whenever I document mine, I can also submit a PR for yours (eg: when 8.1 comes out)
